name: "TS-Builder"

on:
  push:
    branches:
      - "*"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  buildPack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ðŸš€ Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: ðŸš€ Install dependencies
        run: yarn install --frozen-lockfile

      - name: ðŸš€ Build
        run: yarn build

      - name: ðŸš€ Commit packed js
        id: commitPackedJs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./dist
          git commit -m "By GH-Actions"

      - name: ðŸš€ Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: production-build
          force_orphan: true
