name: "build-pack"
on:
  push:
    branches:
      - "*"
jobs:
  buildPack:
    env:
      PACKED_JS_PATH: "dist/index.js"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ðŸš€ xtract branch name
        id: extractBranch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: ðŸš€ Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: ðŸš€ Install dependencies
        run: npm install
      - name: ðŸš€ Build
        run: npm run build
      - name: ðŸš€ Pack
        run: npm run pack
      - name: ðŸš€ Check packed js changes
        id: packedJsStatus
        run: echo ::set-output name=changes::$(git status ${{ env.PACKED_JS_PATH }} --porcelain)
      - name: ðŸš€ Commit packed js
        id: commitPackedJs
        if: steps.packedJsStatus.outputs.changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.PACKED_JS_PATH }}
          git commit -m "Pack with dependencies to ${{ env.PACKED_JS_PATH }}"
      - name: ðŸš€ Push packed js
        if: steps.commitPackedJs.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
          branch: ${{ steps.extractBranch.outputs.branch }}
